language: node_js
node_js:
  - '10'

install:
  - npm install

script:
  - npm run lint
  - npm run generate

after_success:
  # Do not deploy code from pull requests
  - if [ "$TRAVIS_PULL_REQUEST" == "true" ]; then exit; fi
  # Deploy by pushing to a subdirectory in gh-pages branch based on current branch/tag
  - ./node_modules/.bin/gh-pages-multi deploy -d -s dist -t $TRAVIS_BRANCH
