version: '3'
services:

  # DataFair: datasets, application configurations, etc.
  data-fair:
    image: koumoul/data-fair:latest
    network_mode: host
    environment:
      - DIRECTORY_URL=http://localhost:5640
      - OPENAPI_VIEWER_URL=http://localhost:5680

  # Users and organizations compatible with DataFair
  simple-directory:
    image: koumoul/simple-directory:latest
    environment:
      - PUBLIC_URL=http://localhost:5640
      - STORAGE_MONGO_URL=mongodb://mongodb/simple-directory
      - MAILDEV_ACTIVE=true
      - LIST_ENTITIES_MODE=anonymous
    ports:
      - 5640:8080
      - 1080:1080

  # database for data-fair and simple-directory
  mongodb:
    image: mongo:4.1
    ports:
      - 27017:27017

  # indexation engine for data-fair
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  # API documentation viewer for data-fair
  openapi-viewer:
    image: koumoul/openapi-viewer:0.8.0
    ports:
      - 5680:8080
